apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-library-ns
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: lalbudha47/mern-library-backend:v3-k8s
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-configmap
        - secretRef:
            name: backend-secrets
