apiVersion: v1
kind: Namespace
metadata:
  name: mern-library-ns
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mern-library-ns
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: mern-library-ns
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: mern-library-ns
data:
  NODE_ENV: "development"
  PORT: "5000"
  FRONTEND_URL: "http://localhost:3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: mern-library-ns
type: Opaque
data:
  MONGODB_URI: "bW9uZ29kYjovL21vbmdvLXNlcnZpY2U6MjcwMTcvbGlicmFyeQ=="
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-library-ns
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-library-ns
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: lalbudha47/mern-library-backend:v3-k8s
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-configmap
        - secretRef:
            name: backend-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: mern-library-ns
data:
  REACT_APP_API_URL: "http://localhost:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-library-ns
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-library-ns
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lalbudha47/mern-library-frontend:v4-k8s
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-configmap
        command: ["/bin/sh", "-c"]
        args: ["npm start"]