apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-library-ns
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lalbudha47/mern-library-frontend:v4-k8s
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-configmap
        command: ["/bin/sh", "-c"]
        args: ["npm start"]
