apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-library-ns
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:stable
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: static-content
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      initContainers:
      - name: frontend-builder
        image: lalbudha47/mern-library-frontend:v4-k8s
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Building frontend..."
            mkdir -p /static-content
            cp -r /app/* /static-content/
            echo "Creating index.html if it doesn't exist"
            if [ ! -f /static-content/index.html ]; then
              echo "<html><body><h1>MERN Library</h1><p>Welcome to the MERN Library application</p></body></html>" > /static-content/index.html
            fi
            echo "Frontend content copied to static content directory"
            ls -la /static-content/
        volumeMounts:
        - name: static-content
          mountPath: /static-content
        env:
        - name: REACT_APP_API_URL
          value: "http://mern-library.local/api"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: static-content
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: frontend-nginx-config