apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: mern-library-ns
data:
  NODE_ENV: "development"
  PORT: "5000"
  FRONTEND_URL: "http://localhost:3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: mern-library-ns
type: Opaque
data:
  MONGODB_URI: "bW9uZ29kYjovL21vbmdvLXNlcnZpY2U6MjcwMTcvbGlicmFyeQ=="
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-library-ns
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-library-ns
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: lalbudha47/mern-library-backend:v3-k8s
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-configmap
        - secretRef:
            name: backend-secrets
