apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: mern-library-ns
data:
  REACT_APP_API_URL: "http://localhost:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-library-ns
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-library-ns
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lalbudha47/mern-library-frontend:v4-k8s
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-configmap
        command: ["/bin/sh", "-c"]
        args: ["npm start"]
